jobs:
- job: Initialize_Build_SemanticVersion
  timeoutInMinutes: 2
  pool:
    vmImage: windows-latest
    demands:
      - DotNetFramework
      - msbuild

  steps:
  - template: Initialize_Build_SemanticVersion.yml

- job: Initialize_Build
  dependsOn: Initialize_Build_SemanticVersion
  timeoutInMinutes: 10
  variables:
    SemanticVersion: $[dependencies.Initialize_Build_SemanticVersion.outputs['setsemanticversion.SemanticVersion']]
    BuildRevision: $[counter(format('{0}.{1}', variables['SemanticVersion'], variables['build.definitionname']), 1)]

  pool:
    vmImage: windows-latest
    demands:
      - DotNetFramework
      - msbuild

  steps:
  - template: Initialize_Build.yml

- job: Build_and_UnitTest_NonRTM
  dependsOn: Initialize_Build
  timeoutInMinutes: 170
  variables:
    BuildNumber: $[dependencies.Initialize_Build.outputs['updatebuildnumber.BuildNumber']]
    FullVstsBuildNumber: $[dependencies.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
    VsTargetChannel: $[dependencies.Initialize_Build.outputs['updatebuildnumber.VsTargetChannel']]
    VsTargetMajorVersion: $[dependencies.Initialize_Build.outputs['updatebuildnumber.VsTargetMajorVersion']]
    SDKVersionForBuild: $[dependencies.Initialize_Build.outputs['getSDKVersionForBuild.SDKVersionForBuild']]
    LocalizedLanguageCount: "13"
    BuildRTM: "false"

  pool:
    name: VSEng-MicroBuildVS2019
    demands:
      - DotNetFramework
      - msbuild

  steps:
  - template: Build_and_UnitTest.yml

  steps:
  - template: Build_and_UnitTest.yml

- job: Apex_Tests_On_Windows
  dependsOn:
  - Build_and_UnitTest_NonRTM
  - Initialize_Build
  timeoutInMinutes: 120
  variables:
    BuildNumber: $[dependencies.Initialize_Build.outputs['updatebuildnumber.BuildNumber']]
    FullVstsBuildNumber: $[dependencies.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
    SDKVersionForBuild: $[dependencies.Initialize_Build.outputs['getSDKVersionForBuild.SDKVersionForBuild']]
  condition: "and(succeeded(),eq(variables['RunApexTests'], 'true')) "
  pool:
    name: DDNuGet-Windows
    demands:
    - DotNetFramework
    - Allow_NuGet_Apex_Tests -equals false

  steps:
  - template: Apex_Tests_On_Windows.yml
